#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : httpcore
Version  : 0.13.7
Release  : 25
URL      : https://files.pythonhosted.org/packages/6a/90/334411fe5455d30498add7d77a8bf4833bfc4671289a954fb2fd43795338/httpcore-0.13.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/6a/90/334411fe5455d30498add7d77a8bf4833bfc4671289a954fb2fd43795338/httpcore-0.13.7.tar.gz
Summary  : A minimal low-level HTTP client.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: httpcore-license = %{version}-%{release}
Requires: httpcore-python = %{version}-%{release}
Requires: httpcore-python3 = %{version}-%{release}
Requires: anyio
Requires: h11
Requires: h2
Requires: sniffio
BuildRequires : anyio
BuildRequires : buildreq-distutils3
BuildRequires : h11
BuildRequires : h2
BuildRequires : sniffio

%description
# HTTP Core
[![Test Suite](https://github.com/encode/httpcore/workflows/Test%20Suite/badge.svg)](https://github.com/encode/httpcore/actions)
[![Package version](https://badge.fury.io/py/httpcore.svg)](https://pypi.org/project/httpcore/)

%package license
Summary: license components for the httpcore package.
Group: Default

%description license
license components for the httpcore package.


%package python
Summary: python components for the httpcore package.
Group: Default
Requires: httpcore-python3 = %{version}-%{release}

%description python
python components for the httpcore package.


%package python3
Summary: python3 components for the httpcore package.
Group: Default
Requires: python3-core
Provides: pypi(httpcore)
Requires: pypi(anyio)
Requires: pypi(h11)
Requires: pypi(sniffio)

%description python3
python3 components for the httpcore package.


%prep
%setup -q -n httpcore-0.13.7
cd %{_builddir}/httpcore-0.13.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635740132
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/httpcore
cp %{_builddir}/httpcore-0.13.7/LICENSE.md %{buildroot}/usr/share/package-licenses/httpcore/cc8ca9a1480585587761018c62aca50f1cbb0594
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/httpcore/cc8ca9a1480585587761018c62aca50f1cbb0594

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
